model_name: model_laptop
# --- Architecture ---
num_heads: 8
num_layers: 6
embed_dim: 384
ff_hidden_dim: 1536
max_length: 256
vocab_size: 50257
output_dim: 50257
# --- Regularization ---
qkv_bias: false
mha_dropout_rate: 0.1
ffn_dropout_rate: 0.1
emb_dropout_rate: 0.1
layer_norm_eps: 0.00001
# --- Optimization ---
learning_rate: 0.0006     
weight_decay: 0.1
min_lr: 6e-5               
warmup_steps: 200
# --- Training Loop Dynamics ---
micro_batch_size: 32       
grad_accumulation: 4 
num_epochs: 1
# --- Checkpointing & Eval ---
eval_freq: 100             
eval_iter: 10
temperature: 1.2
top_k: 50
top_p: 0.95
checkpoint_name: last
checkpoint_path: checkpoint
# --- Inference ---
prompt: Once upon a time
max_new_tokens: 250
