model_name: model_laptop
num_heads: 8            
num_layers: 6
embed_dim: 384         
ff_hidden_dim: 1536     
max_length: 256          
vocab_size: 50257
output_dim: 50257
qkv_bias: false
mha_dropout_rate: 0.1
ffn_dropout_rate: 0.1
emb_dropout_rate: 0.1
layer_norm_eps: 0.00001
learning_rate: 0.0005
weight_decay: 0.1
num_epochs: 1
eval_freq: 20
eval_iter: 5
temperature: 1.5
top_k: null
top_p: null
use_checkpoint: last
checkpoint_path: checkpoint
min_lr: 1e-6
warmup_steps: 300